# Generated by Django 5.2.7 on 2025-11-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ethanolapp", "0003_passwordresetrequest_alter_passwordresettoken_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.CharField(max_length=255),
        ),
    ]
