# Generated by Django 5.2.7 on 2025-11-29 05:56

from django.db import migrations, models
import uuid

def generate_uids(apps, schema_editor):
    Profile = apps.get_model('ethanolapp', 'Profile')
    for profile in Profile.objects.all():
        if not profile.uid:
            # Generate a unique UID
            while True:
                new_uid = f"USR-{uuid.uuid4().hex[:8].upper()}"
                if not Profile.objects.filter(uid=new_uid).exists():
                    profile.uid = new_uid
                    profile.save(update_fields=['uid'])
                    break

class Migration(migrations.Migration):

    dependencies = [
        ("ethanolapp", "0004_alter_passwordresettoken_token"),  # previous migration
    ]

    operations = [
        # Add profilePic field
        migrations.AddField(
            model_name="profile",
            name="profilePic",
            field=models.ImageField(upload_to="profiles/", null=True, blank=True),
        ),

        # Add UID field (initially without unique=True)
        migrations.AddField(
            model_name="profile",
            name="uid",
            field=models.CharField(max_length=20, blank=True, null=True),
        ),

        # Populate UID for existing profiles
        migrations.RunPython(generate_uids),

        # Make UID unique
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(max_length=20, unique=True, blank=True, null=True),
        ),
    ]
