# Generated by Django 5.2.7 on 2025-11-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ethanolapp", "0006_alter_profile_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
