# Generated by Django 5.2.7 on 2025-12-02 05:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ethanolapp", "0007_alter_profile_uid"),
    ]

    operations = [
        migrations.CreateModel(
            name="MolassesReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("type", models.CharField(max_length=50)),
                ("brix", models.FloatField()),
                ("pol", models.FloatField()),
                ("volume", models.FloatField()),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
