# Generated by Django 5.2.7 on 2025-12-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ethanolapp", "0008_molassesreading"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="molassesreading",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RemoveField(
            model_name="molassesreading",
            name="type",
        ),
        migrations.AddField(
            model_name="molassesreading",
            name="purity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="molassesreading",
            name="source",
            field=models.CharField(default="molasses", max_length=50),
        ),
        migrations.AlterField(
            model_name="molassesreading",
            name="brix",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="molassesreading",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="molassesreading",
            name="pol",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="molassesreading",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="molassesreading",
            name="volume",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
