# Generated by Django 5.1.1 on 2025-12-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ethanolapp", "0009_alter_molassesreading_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresettoken",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
