# Generated by Django 5.1.1 on 2025-12-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ethanolapp", "0011_activitylog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitylog",
            name="day",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="hour",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="minute",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="month",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="second",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="week",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="year",
        ),
        migrations.AddField(
            model_name="activitylog",
            name="action",
            field=models.CharField(default="view", max_length=100),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="module",
            field=models.CharField(default="system", max_length=100),
        ),
    ]
