# Generated by Django 5.1.1 on 2025-12-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ethanolapp", "0012_remove_activitylog_day_remove_activitylog_hour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="day",
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="hour",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="minute",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="month",
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="second",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="week",
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="year",
            field=models.IntegerField(default=2025, editable=False),
        ),
    ]
