# Generated by Django 5.1.1 on 2025-12-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ethanolapp",
            "0013_activitylog_day_activitylog_hour_activitylog_minute_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ethanol", models.FloatField()),
                ("feedstock", models.FloatField()),
                ("water", models.FloatField()),
                ("emissions", models.FloatField()),
                ("supply", models.FloatField()),
                ("north", models.FloatField(default=0)),
                ("south", models.FloatField(default=0)),
                ("east", models.FloatField(default=0)),
                ("west", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
