# Generated by Django 5.1.1 on 2025-12-12 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ethanolapp", "0014_productionmetric"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductionMetric",
        ),
    ]
