# Generated by Django 6.0.5 on 2026-06-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethanolapp', '0015_delete_productionmetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='year',
            field=models.IntegerField(default=2026, editable=False),
        ),
    ]
